---
title: <center>Software Development Essentials</center>
output:
  html_document:
    toc: false
    toc_float: 
      collapsed: false
    toc_depth: 2
---
<style>
.two-column {
  padding: 1em;
  -moz-column-count: 2;
  -moz-column-gap: 1em;
  -webkit-column-count: 2;
  -webkit-column-gap: 1em;
  column-count: 2;
  column-gap: 1em;
}
</style>

注：此網站只可用作學習。禁止以任何形式使用或傳播此網站的任何內容。

#Sorting Algorithm by R
- [Selection Sort](Sorting.html)

#Calendar{.tabset}
##Algorithm Class

<div class="two-column">

- [Practice 1](Algorithm_Class_1_Practice.html), 6/30, Classes, objects, and references (I)
- [Practice 2](Algorithm_Class_2_Practice.html), 7/1, Classes, objects, and references (II)
- [Practice 3](Algorithm_Class_3_Practice.html), 7/2, Practice Problems

- [Class 2](Algorithm_Class_2_Lecture.html), 7/4, Recursion I & Binary Search
- [Practice 4](Algorithm_Class_4_Practice.html), 7/6, Linked List and Java List

- [Class 3](Algorithm_Class_3_Lecture.html), 7/7, Queue & Stack
- [Practice 5](Algorithm_Class_5_Practice.html), 7/8, Practice Problems

- [Class 4](Algorithm_Class_4_Lecture.html), 7/9, LinkedList
- [Practice 6](Algorithm_Class_6_Practice.html), 7/11, Queue, Stack, and Deque

- [Class 5](Algorithm_Class_5_Lecture.html), 7/13, Binary Tree & Binary Search Tree
- [Practice 7](Algorithm_Class_7_Practice.html), 7/14, Binary Tree 1
- [Practice 8](Algorithm_Class_8_Practice.html), 7/15, Binary Trees 2

- [Class 6](Algorithm_Class_6_Lecture.html), 7/16, Heap & Graph Search Algorithms 1
- [Practice 9](Algorithm_Class_9_Practice.html), 7/18, Heap in Java (PriorityQueue)

- [Class 7](Algorithm_Class_7_Lecture.html), 7/20, Graph Search Algorithms 2 (DFS)
- [Practice 10](Algorithm_Class_10_Practice.html), 7/21, Implementing Heaps
- [Practice 11](Algorithm_Class_11_Practice.html), 7/22, Practice Problems

- [Class 8](Algorithm_Class_8_Lecture.html), 7/23, HashTable & String 1
- [Practice 12](Algorithm_Class_12_Practice.html), 7/25
- [Practice 13](Algorithm_Class_13_Practice.html), 7/27

- [Class 9](Algorithm_Class_9_Lecture.html), 7/28
- [Class 10](Algorithm_Class_10_Lecture.html), 7/29

- [Homework 1](Algorithm_Class_1_hw.html)
- [Homework 2](Algorithm_Class_2_hw.html)
- [Homework 3](Algorithm_Class_3_hw.html)
- [Homework 4](Algorithm_Class_4_hw.html)

</div>

##Algorithm Beginner Class

<div class="two-column">

- [Lecture 1](Algorithm_Beginner_Class_1_Lec.html), 5/29, Java Basics I
- [Homework 1*](Algorithm_Beginner_Class_1_hw.html)

- [Lecture 2](Algorithm_Beginner_Class_2_Lec.html), 5/31, Java Basics II
- [Homework 2*](Algorithm_Beginner_Class_2_hw.html)

- [Lecture 3](Algorithm_Beginner_Class_3_Lec.html), 6/2, Java Basics III
- [Homework 3*](Algorithm_Beginner_Class_3_hw.html)

- [Lecture 4](Algorithm_Beginner_Class_4_Lec.html), 6/5, Java Basics IV
- [Homework 4*](Algorithm_Beginner_Class_4_hw.html)

- [Lecture 5](Algorithm_Beginner_Class_5_Lec.html), 6/7, Sorting Algorithms 1
- [Homework 5](Algorithm_Beginner_Class_5_hw.html)

- [Lecture 6](Algorithm_Beginner_Class_6_Lec.html), 6/9, Sorting Algorithms 2
- [Homework 6](Algorithm_Beginner_Class_6_hw.html)

- [Lecture 7](Algorithm_Beginner_Class_7_Lec.html), 6/12, Recursion, Queue, Stack
- [Homework 7](Algorithm_Beginner_Class_7_hw.html)

- [Lecture 8](Algorithm_Beginner_Class_8_Lec.html), 6/14, Queue & Linked List
- [Homework 8](Algorithm_Beginner_Class_8_hw.html)

- [Lecture 9](Algorithm_Beginner_Class_9_Lec.html), 6/16, LinkedList
- [Homework 9](Algorithm_Beginner_Class_9_hw.html)

- [Lecture 10](Algorithm_Beginner_Class_10_Lec.html), 6/19, Binary Search
- [Homework 10](Algorithm_Beginner_Class_10_hw.html)

- [Lecture 11](Algorithm_Beginner_Class_11_Lec.html), 6/21, Binary Tree
- [Homework 11](Algorithm_Beginner_Class_11_hw.html)

- [Lecture 12](Algorithm_Beginner_Class_12_Lec.html), 6/23, Binary Tree and Binary Search Tree
- [Homework 12](Algorithm_Beginner_Class_12_hw.html)

- [Lecture 13](Algorithm_Beginner_Class_13_Lec.html), 6/26, Heap
- [Homework 13](Algorithm_Beginner_Class_13_hw.html)

- [Lecture 14](Algorithm_Beginner_Class_14_Lec.html), 6/28, Graph
- [Homework 14](Algorithm_Beginner_Class_14_hw.html)

</div>
